# Generated by Django 3.1.3 on 2020-11-11 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0004_auto_20201111_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='logos',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 11, 18, 13, 29, 500746)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 11, 18, 13, 29, 500715)),
        ),
    ]
