# Generated by Django 3.1.3 on 2020-11-11 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0005_auto_20201111_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='logos',
            field=models.ImageField(default=None, null=True, upload_to='uploads/airline_logos'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 11, 18, 15, 20, 121798)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 11, 18, 15, 20, 121768)),
        ),
    ]
