# Generated by Django 3.1.3 on 2020-11-19 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0009_auto_20201116_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab_Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_number', models.PositiveSmallIntegerField(default=9999999990)),
                ('driver_rating', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='cab',
            name='air_conditioned',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='price',
        ),
        migrations.AddField(
            model_name='car_options',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car_options',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 19, 21, 18, 26, 33373)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 19, 21, 18, 26, 33343)),
        ),
    ]
