# Generated by Django 3.1.1 on 2020-11-20 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0014_auto_20201120_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image2',
            field=models.ImageField(default=None, null=True, upload_to='uploads/hotel_photos'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image3',
            field=models.ImageField(default=None, null=True, upload_to='uploads/hotel_photos'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image4',
            field=models.ImageField(default=None, null=True, upload_to='uploads/hotel_photos'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image5',
            field=models.ImageField(default=None, null=True, upload_to='uploads/hotel_photos'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 20, 16, 24, 42, 321839)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 20, 16, 24, 42, 321839)),
        ),
    ]
