# Generated by Django 3.1.3 on 2020-11-22 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0016_auto_20201120_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='bluetooth_song',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cab',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cab',
            name='number_plate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 22, 18, 6, 6, 57240)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 22, 18, 6, 6, 57198)),
        ),
    ]
