# Generated by Django 3.1.3 on 2020-11-22 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0017_auto_20201122_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab_driver',
            name='driver_photo',
            field=models.ImageField(default=None, null=True, upload_to='uploads/driver_photo'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 22, 18, 44, 47, 586890)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 22, 18, 44, 47, 586858)),
        ),
    ]
