# Generated by Django 3.1.3 on 2020-11-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0019_auto_20201122_1921'),
        ('Travel', '0017_auto_20201122_1849'),
    ]

    operations = [
    ]
