# Generated by Django 3.1.1 on 2020-11-23 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0021_auto_20201123_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='locality',
            field=models.CharField(default='X', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street',
            field=models.CharField(default='Y', max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 23, 20, 36, 1, 396188)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 23, 20, 36, 1, 396188)),
        ),
    ]
