# Generated by Django 3.1.2 on 2020-11-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0022_auto_20201123_1539'),
        ('Travel', '0022_auto_20201123_2036'),
    ]

    operations = [
    ]
