# Generated by Django 3.1.3 on 2020-11-24 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0026_auto_20201124_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_rating',
            old_name='rating',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 24, 11, 42, 2, 233784)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 24, 11, 42, 2, 233749)),
        ),
    ]
