# Generated by Django 3.1.3 on 2020-11-24 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0027_auto_20201124_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_rating',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 24, 12, 22, 44, 294938)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 24, 12, 22, 44, 294908)),
        ),
    ]
