# Generated by Django 3.1.1 on 2020-11-25 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0032_auto_20201125_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_booking',
            name='room_type',
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='deluxe_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='premium_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='standard_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='suite_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel_booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 25, 14, 38, 58, 919251)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 25, 14, 38, 58, 919251)),
        ),
    ]
