# Generated by Django 3.1.1 on 2020-11-25 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0033_auto_20201125_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight_booking',
            old_name='number_of_business_tickets',
            new_name='business_number',
        ),
        migrations.RenameField(
            model_name='flight_booking',
            old_name='number_of_economy_tickets',
            new_name='economy_number',
        ),
        migrations.RemoveField(
            model_name='flight_booking',
            name='customer',
        ),
        migrations.AddField(
            model_name='flight_booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='flight_booking',
            name='user_email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='flight_booking',
            name='user_fname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='flight_booking',
            name='user_lname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 26, 2, 38, 15, 178508)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 26, 2, 38, 15, 178508)),
        ),
    ]
