# Generated by Django 3.1.1 on 2020-11-25 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0034_auto_20201126_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(default='', max_length=50)),
                ('user_fname', models.CharField(default='', max_length=50)),
                ('user_lname', models.CharField(default='', max_length=50)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('source', models.CharField(default='', max_length=50)),
                ('destination', models.CharField(default='', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('car', models.CharField(default='', max_length=50)),
                ('driver', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 26, 3, 17, 26, 508876)),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 26, 3, 17, 26, 508876)),
        ),
    ]
