# Generated by Django 3.1.2 on 2020-11-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0039_auto_20201126_2131'),
        ('Travel', '0036_auto_20201127_0226'),
    ]

    operations = [
    ]
